on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  BuildPublish:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          source-revision: f13fa9e9f338fd4558ef9237848bc2e6436775b7
          use-gha-cache: false
      - run: nix build .#nixosConfigurations.ethercalc-demo.config.system.build.toplevel
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "DeterminateSystems/demo"
          rolling: true
          visibility: "private"
          include-output-paths: true
