name: CI

on:
  pull_request:
  push:
    branches: [main]
jobs:
  format-build:
    runs-on: ubuntu-latest
    env:
      IDS_HOST: https://test-install-determinate-systems.fly.dev/
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action-priv@diag
      - uses: DeterminateSystems/magic-nix-cache-action-priv@diag
      - name: Check rustfmt
        run: nix develop --command cargo fmt -- --check
      - run: nix build -L
