name: CI

on:
  pull_request:
  push:
    branches: [main]
jobs:
  format-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check rustfmt
        run: nix develop --command cargo fmt -- --check
      - run: nix build -L
